name: Valorant Profiler

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run dist
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}

      - name: Package Electron App
        run: npm run dist